SQL:
  enable: false
  table: "dragoncore"
  hostname: "127.0.0.1"
  port: "3306"
  #数据库名，库需要自己创建，否则连接失败
  database: "database"
  username: "root"
  password: "root"
  # 最大连接数(默认为处理器数*2)
  maxconnections: 0
  properties:
    - "useSSL=false"
    - "useUnicode=true"
    - "characterEncoding=utf8"

# 玩家背包数据目录(当SQL为false时可以使用该选项)
# 填空则是以插件目录内的PlayerData进行保存
PlayerDataFolder: ""

JoinPacketDelay: 60

# 压缩包需放在DragonCore目录下，并命名为Resource.zip
Password: "压缩包密码"

# 若删除这条配置则不会修改标题
ClientTitle: "欢迎使用龙之核心,该标题可在config.yml修改"

# 聊天若输入渐变格式，会变成渐变色文本
replaceChatColor: true

# 是否兼容AP属性插件
AttributePlus: true
# 是否兼容SX属性插件
SX-Attribute: true
# 是否兼容龙之时装付费版
DragonArmourers: false

# 提示：所有文件(除了config.yml)均可创建一个同名的文件夹，里面任意的yml均会载入
# 例如插件存在EntityModel.yml
# 则可以创建一个文件夹EntityModel，里面的所有yml文件都会载入
# DragonCore/
#  - EntityModel/
#    - 日系汽车.yml
#    - 国产汽车.yml

ScriptTools:
  # 这四个已默认拥有,不需要添加
  #PlaceholderAPI: "me.clip.placeholderapi.PlaceholderAPI"
  #Bukkit: "org.bukkit.Bukkit"
  #Arrays: "java.util.Arrays"
  #SlotAPI: "eos.moe.dragoncore.api.SlotAPI"