SQL:
  enable: true

# 玩家背包数据目录(当SQL为false时可以使用该选项)
# 填空则是以插件目录内的PlayerData进行保存
PlayerDataFolder: ""

JoinPacketDelay: 40

# 压缩包需放在DragonCore目录下，并命名为Resource.zip
Password: "压缩包密码"

# 若删除这条配置则不会修改标题
ClientTitle: "欢迎使用龙之核心,该标题可在config.yml修改"

# 聊天若输入渐变格式，会变成渐变色文本
replaceChatColor: true

# 是否兼容龙之时装付费版
DragonArmourers: false

ScriptTools:
  # 这四个已默认拥有,不需要添加
  #PlaceholderAPI: "me.clip.placeholderapi.PlaceholderAPI"
  #Bukkit: "org.bukkit.Bukkit"
  #Arrays: "java.util.Arrays"
  #SlotAPI: "eos.moe.dragoncore.api.SlotAPI"