SQL:
  enable: true

# 玩家背包数据目录(当SQL为false时可以使用该选项)
# 填空则是以插件目录内的PlayerData进行保存
PlayerDataFolder: ""

JoinPacketDelay: 40

# 压缩包需放在DragonCore目录下，并命名为Resource.zip
Password: "压缩包密码"

# 聊天若输入渐变格式，会变成渐变色文本
replaceChatColor: true

# 是否兼容龙之时装付费版
DragonArmourers: true