name: DragonCore
main: net.sakuragame.eternal.dragoncore.DragonCore
version: ${project.version}
depend:
  - MegumiLib
  - DataManager
  - PlaceholderAPI
  - NBTAPI
softdepend:
  - MythicMobs
  - DragonArmourers
commands:
  dragoncore:
    aliases:
      - core