name: DragonCore
main: eos.moe.dragoncore.DragonCore
version: ${project.version}
depend:
  - DataManager
  - PlaceholderAPI
softdepend:
  - MythicMobs
  - DragonArmourers
commands:
  dragoncore:
    aliases:
      - core