name: DragonCore
main: net.sakuragame.eternal.dragoncore.DragonCore
version: ${project.version}
depend:
  - MegumiLib
  - DataManager-Bukkit
  - PlaceholderAPI
  - NBTAPI
  - EternalCargo
softdepend:
  - MythicMobs
  - DragonArmourers
  - Skript
commands:
  dragoncore:
    aliases:
      - core