glasses_slot:
  skin: false
eardrop_slot:
  skin: false
gloves_slot:
  skin: false
ring1_slot:
  skin: false
ring2_slot:
  skin: false
ring3_slot:
  skin: false
ring4_slot:
  skin: false
medal_slot:
  skin: false
honor_slot:
  skin: false
potion_slot:
  skin: false
pet_egg_slot:
  skin: false

suit_skin:
  skin: true
  skin-type: 0
mainhand_skin:
  skin: true
offhand_skin:
  skin: true
handwear_skin:
  skin: true
  skin-type: 1
clothes_skin:
  skin: true
  skin-type: 1
pants_skin:
  skin: true
  skin-type: 1
shoes_skin:
  skin: true
  skin-type: 1
wings_1_skin:
  skin: true
  skin-type: 2
wings_2_skin:
  skin: true
  skin-type: 2