glasses_slot:
  skin: false
eardrop_slot:
  skin: false
cloak_slot:
  skin: false
ring1_slot:
  skin: false
ring2_slot:
  skin: false
ring3_slot:
  skin: false
ring4_slot:
  skin: false
medal_slot:
  skin: false
honor_slot:
  skin: false
pet_egg_slot:
  skin: false
pet_saddle_slot:
  skin: false
pet_equip1_slot:
  skin: false
pet_equip2_slot:
  skin: false
pet_equip3_slot:
  skin: false

suit_skin:
  skin: true
mainhand_skin:
  skin: true
offhand_skin:
  skin: true
handwear_skin:
  skin: true
clothes_skin:
  skin: true
pants_skin:
  skin: true
shoes_skin:
  skin: true
wings_1_skin:
  skin: true
wings_2_skin:
  skin: true